"""Subset the open fonts down to the glyphs the pages actually use and inline them
into fonts.css, so both pages render identically offline and in headless Chromium.

usage: python3 build_fonts.py <dir with the downloaded Google Fonts .ttf files>
"""
import base64, io, pathlib, sys
from fontTools import subset
from fontTools.ttLib import TTFont

HERE = pathlib.Path(__file__).parent
SRC = pathlib.Path(sys.argv[1])
FACES = [
    ("K Serif", 600, "NotoSerifSC-600.ttf"), ("K Serif", 900, "NotoSerifSC-900.ttf"),
    ("K Sans", 400, "NotoSansSC-400.ttf"), ("K Sans", 500, "NotoSansSC-500.ttf"),
    ("K Sans", 700, "NotoSansSC-700.ttf"), ("K Sans", 900, "NotoSansSC-900.ttf"),
    ("K Kr", 500, "NotoSansKR-500.ttf"), ("K Kr", 700, "NotoSansKR-700.ttf"), ("K Kr", 900, "NotoSansKR-900.ttf"),
    ("K Cond", 500, "BarlowCondensed-500.ttf"), ("K Cond", 700, "BarlowCondensed-700.ttf"),
    ("K Mono", 400, "IBMPlexMono-400.ttf"), ("K Mono", 500, "IBMPlexMono-500.ttf"),
]

text = "".join(chr(c) for c in range(0x20, 0x7F)) + "₩×−–—≈→←↓↑“”‘’·…，。：；？！、（）《》【】＋"
for f in ["doc.html", "engine.js", "timeline.js", "narration.json"]:
    p = HERE / f
    if p.exists():
        text += p.read_text(encoding="utf-8")
chars = "".join(sorted(set(text)))

css = ["/* generated by build_fonts.py: subsets of Noto Serif SC, Noto Sans SC, Noto Sans KR,\n   Barlow Condensed and IBM Plex Mono (all SIL Open Font License). */"]
for family, weight, fn in FACES:
    opts = subset.Options()
    opts.flavor = "woff2"
    opts.layout_features = ["*"]
    opts.name_IDs = ["*"]
    font = TTFont(SRC / fn)
    sub = subset.Subsetter(opts)
    sub.populate(text=chars)
    sub.subset(font)
    buf = io.BytesIO()
    font.flavor = "woff2"
    font.save(buf)
    b64 = base64.b64encode(buf.getvalue()).decode()
    css.append(f"@font-face{{font-family:'{family}';font-weight:{weight};font-style:normal;font-display:block;src:url(data:font/woff2;base64,{b64}) format('woff2');}}")
    print(f"{family} {weight}: {len(buf.getvalue())//1024} KB")
(HERE / "fonts.css").write_text("\n".join(css) + "\n", encoding="utf-8")
