import { Router, type IRouter } from "express";
import healthRouter from "./health";
import hallOfFameRouter from "./hall-of-fame";
import authRouter from "./auth";
import moodCheckInsRouter from "./mood-checkins";
import orgStructureRouter from "./org-structure";
import adminUsersRouter from "./admin-users";
import birthdaysRouter from "./birthdays";
import achievementsRouter from "./achievements";
import guinnessRecordsRouter from "./guinness-records";
import goalsRouter from "./goals";
import quizRouter from "./quiz";
import wordleRouter from "./wordle";
import pointsRouter from "./points";
import profileCustomizationRouter from "./profile-customization";
import activityHistoryRouter from "./activity-history";
import mentorsRouter from "./mentors";
import learningRouter from "./learning";
import gratitudeRouter from "./gratitude";
import notificationsRouter from "./notifications";
import presenceRouter from "./presence";
import betsRouter from "./bets";
import challengesRouter from "./challenges";
import socialRouter from "./social";
import dmRouter from "./dm";
import rewardsRouter from "./rewards";
import postsRouter from "./posts";
import filesRouter from "./files";
import progressPhotosRouter from "./progress-photos";
import birthdayEmailSettingsRouter from "./birthday-email-settings";
import pushRouter from "./push";
import turnCredentialsRouter from "./turn-credentials";
import voiceRouter from "./voice";
import pkRouter from "./pk";

const router: IRouter = Router();

router.use(healthRouter);
router.use(hallOfFameRouter);
router.use(authRouter);
router.use(moodCheckInsRouter);
router.use(orgStructureRouter);
router.use(adminUsersRouter);
router.use(birthdaysRouter);
router.use(achievementsRouter);
router.use(guinnessRecordsRouter);
router.use(goalsRouter);
router.use(quizRouter);
router.use(wordleRouter);
router.use(pointsRouter);
router.use(profileCustomizationRouter);
router.use(activityHistoryRouter);
router.use(mentorsRouter);
router.use(learningRouter);
router.use(gratitudeRouter);
router.use(notificationsRouter);
router.use(presenceRouter);
router.use(betsRouter);
router.use(challengesRouter);
router.use(socialRouter);
router.use(dmRouter);
router.use(rewardsRouter);
router.use(postsRouter);
router.use(filesRouter);
router.use(progressPhotosRouter);
router.use(birthdayEmailSettingsRouter);
router.use(pushRouter);
router.use(turnCredentialsRouter);
router.use(voiceRouter);
router.use(pkRouter);

export default router;
