$ErrorActionPreference = "Stop"

$root = Split-Path -Parent $PSScriptRoot
$sourceSchema = Join-Path $root "artifacts/engagement-hub/supabase/schema.sql"
$outputPath = Join-Path $root "lib/db/digitalocean-baseline.sql"

$schema = [System.IO.File]::ReadAllText($sourceSchema)
$schema = [regex]::Replace($schema, '(?m)^\\(un)?restrict[^\r\n]*\r?\n', "")
$schema = [regex]::Replace($schema, '(?m)^SET transaction_timeout = 0;\r?\n', "")
$schema = [regex]::Replace($schema, '(?m)^ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin[^\r\n]*\r?\n', "")
$schema = $schema.Replace("CREATE SCHEMA public;", "CREATE SCHEMA IF NOT EXISTS public;")
foreach ($obsoleteFunction in @("push_new_notification", "trigger_birthday_emails")) {
  $functionPattern = "(?s)CREATE FUNCTION public\.$obsoleteFunction\(\).*?\$\$;"
  if (-not [regex]::IsMatch($schema, $functionPattern)) {
    throw "The obsolete hosted-delivery function $obsoleteFunction was not found in the captured schema."
  }
  $schema = [regex]::Replace($schema, $functionPattern, "-- $obsoleteFunction is supplied by the DigitalOcean API worker.")
}

# The captured schema also has a trigger and ACL statements for the hosted
# push function. Drop these with the function itself; the API-owned outbox
# migration installs the replacement trigger later in the baseline.
$hostedPushTrigger = '(?m)^CREATE TRIGGER on_notification_push AFTER INSERT ON public\.notifications FOR EACH ROW EXECUTE FUNCTION public\.push_new_notification\(\);\s*'
if (-not [regex]::IsMatch($schema, $hostedPushTrigger)) {
  throw "The captured schema's hosted push trigger was not found; refusing to build an incomplete baseline."
}
$schema = [regex]::Replace($schema, $hostedPushTrigger, "-- Hosted push trigger is replaced by the API-owned outbox migration.`r`n")
$schema = [regex]::Replace($schema, '(?m)^(?:GRANT|REVOKE) ALL ON FUNCTION public\.(?:push_new_notification\(\)|trigger_birthday_emails\(\)) (?:TO|FROM) [^;]+;\s*', "")

# DigitalOcean owns employee identity in public.profiles plus app-managed
# credentials. Remove only the Auth-managed FK from the portable copy.
$profileAuthForeignKey = '(?s)--\s*\r?\n-- Name: profiles profiles_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -\r?\n--\s*\r?\nALTER TABLE ONLY public\.profiles\s+ADD CONSTRAINT profiles_id_fkey FOREIGN KEY \(id\) REFERENCES auth\.users\(id\) ON DELETE CASCADE;\s*'
if (-not [regex]::IsMatch($schema, $profileAuthForeignKey)) {
  throw "The source schema's Supabase Auth profile foreign key was not found; refusing to build a potentially incomplete baseline."
}
$schema = [regex]::Replace($schema, $profileAuthForeignKey, "")

$pkRules = [System.IO.File]::ReadAllText((Join-Path $root "artifacts/engagement-hub/supabase/migrations/0051_pk_rules_v343.sql"))
$pkCloudJobs = '(?s)\r?\ndo \$\$\s*declare t text;.*?\r?\n\$\$;'
if (-not [regex]::IsMatch($pkRules, $pkCloudJobs)) {
  throw "The PK migration's hosted realtime/cron block was not found; refusing to include cloud-only setup."
}
$pkRules = [regex]::Replace($pkRules, $pkCloudJobs, "`r`n-- Hosted realtime and pg_cron setup is replaced by the API and Droplet jobs.")

$parts = [System.Collections.Generic.List[string]]::new()
$parts.Add("-- Generated by scripts/assemble-digitalocean-baseline.ps1. Apply only to a new, empty tenant database after scripts/digitalocean-schema-preamble.sql has been run by the PostgreSQL administrator.")
$parts.Add("-- Existing application tables, functions, indexes, constraints, and triggers from the captured schema.")
$parts.Add($schema)
$parts.Add("SET search_path = public;")
$accountApproval = [System.IO.File]::ReadAllText((Join-Path $root "artifacts/engagement-hub/supabase/migrations/0049_account_approval.sql"))
$accountApproval = [regex]::Replace($accountApproval, '(?s)-- Pending accounts must not be able to upload into the shared photo bucket\..*?notify pgrst, ''reload schema'';\s*', "-- Supabase Storage policies and PostgREST notifications are not used by the DigitalOcean API.")
$parts.Add("-- Account approval and pending-user behavior added after the captured schema snapshot.")
$parts.Add($accountApproval)
$hofDepartmentVisibility = [System.IO.File]::ReadAllText((Join-Path $root "artifacts/engagement-hub/supabase/migrations/0050_hof_department_visibility.sql"))
$hofDepartmentVisibility = $hofDepartmentVisibility.Replace("notify pgrst, 'reload schema';", "-- PostgREST schema notification is not used by the DigitalOcean API.")
$parts.Add("-- Hall of Fame department visibility added after the captured schema snapshot.")
$parts.Add($hofDepartmentVisibility)
$parts.Add("-- Current PK rules; the hosted publication and cron setup has been removed.")
$parts.Add(@'
-- PK schema updates introduced after the captured application snapshot.
ALTER TABLE public.challenge_participants ADD COLUMN IF NOT EXISTS missed_count integer NOT NULL DEFAULT 0;
ALTER TABLE public.pk_settings
  ADD COLUMN IF NOT EXISTS reminders_enabled boolean NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS announce_live boolean NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS announce_winner boolean NOT NULL DEFAULT true;
CREATE TABLE IF NOT EXISTS public.pk_violations (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  challenge_id uuid NOT NULL REFERENCES public.challenges(id) ON DELETE CASCADE,
  user_id uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  kind text NOT NULL DEFAULT 'missed_updates',
  note text,
  created_at timestamptz NOT NULL DEFAULT now(),
  resolved_at timestamptz,
  resolved_by uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
  resolution text
);
'@)
$parts.Add($pkRules)
$parts.Add("-- Features added after the captured schema snapshot.")
$learningAndGratitude = [System.IO.File]::ReadAllText((Join-Path $root "artifacts/engagement-hub/supabase/migrations/0052_learning_hub_and_gratitude.sql"))
$learningAndGratitude = $learningAndGratitude.Replace("-- Apply this migration to both the C9MYR and C6 Supabase projects.", "-- Apply this schema independently to the C9 and C6 tenant databases.")
$parts.Add($learningAndGratitude)
$parts.Add([System.IO.File]::ReadAllText((Join-Path $root "artifacts/engagement-hub/supabase/migrations/0057_hof_team_members.sql")))
$parts.Add("-- DigitalOcean API sessions, mood check-ins, presence, push queue, voice, and authenticated PK context.")
foreach ($migration in @(
    "0001_api_sessions_and_hof.sql",
    "0002_daily_mood_checkins.sql",
    "0003_app_presence.sql",
    "0004_app_push_delivery.sql",
    "0005_voice_realtime_replacement.sql"
)) {
  $parts.Add([System.IO.File]::ReadAllText((Join-Path $root "lib/db/migrations/$migration")))
}

[System.IO.File]::WriteAllText($outputPath, ($parts -join "`r`n`r`n"), [System.Text.UTF8Encoding]::new($false))
Write-Output "Wrote $outputPath"
