"""Regenerates src/components/goals-tree-foliage-mask.ts from the tree artwork.

Run from artifacts/engagement-hub:  python3 scripts/generate-tree-foliage-mask.py
Requires: pillow, numpy, scipy.

The mask marks the leafy canopy only (leaves, flowers, the glowing sparkles
between them). Trunk, exposed branches, stray falling leaves and everything in
the background are excluded. Both theme images are traced and intersected so a
single mask is safe for either theme, then downsampled conservatively (a cell
counts as foliage only if every source pixel in it is foliage).
"""
import numpy as np
from PIL import Image
from scipy import ndimage as nd

IMAGES = ["public/tree-bg.png", "public/tree-bg-light.png"]
OUT = "src/components/goals-tree-foliage-mask.ts"
CELL = 2  # source pixels per mask cell


def trace(path):
    rgb = Image.open(path).convert("RGB")
    hsv = np.asarray(rgb.convert("HSV")).astype(float)
    h, s, v = hsv[..., 0] * 360 / 255, hsv[..., 1] / 255, hsv[..., 2] / 255
    H, W = h.shape
    green = (h > 55) & (h < 170) & (s > 0.25) & (v > 0.18)
    sparkle = (h > 35) & (h <= 55) & (s > 0.3) & (v > 0.5)
    fol = green | sparkle
    yy, xx = np.mgrid[0:H, 0:W]
    fol &= (xx > W * 0.27) & (xx < W * 0.73) & (yy < H * 0.74)
    fol = nd.binary_opening(fol, iterations=1)
    fol = nd.binary_closing(fol, structure=np.ones((3, 3)), iterations=3)
    fol = largest(fol)
    fol = nd.binary_fill_holes(fol)  # flowers sit inside the leaves
    wood = ((h < 40) | (h > 330)) & (s > 0.35) & (v > 0.25)
    wood = nd.binary_opening(wood, iterations=1)
    # Flower centres and sparkles share the trunk's warm hue; only large
    # connected warm regions (trunk and branches) count as wood.
    lab, n = nd.label(wood)
    sizes = nd.sum(wood, lab, range(1, n + 1))
    wood = np.isin(lab, np.nonzero(sizes >= 600)[0] + 1)
    wood = nd.binary_dilation(wood, iterations=2)
    fol &= ~wood
    fol = nd.binary_opening(fol, structure=np.ones((5, 5)))
    return largest(fol)


def largest(m):
    lab, n = nd.label(m)
    sizes = nd.sum(m, lab, range(1, n + 1))
    return lab == (np.argmax(sizes) + 1)


def main():
    masks = [trace(p) for p in IMAGES]
    fol = np.logical_and.reduce(masks)
    H, W = fol.shape
    h, w = H // CELL, W // CELL
    cells = fol[: h * CELL, : w * CELL].reshape(h, CELL, w, CELL).all(axis=(1, 3))
    rows = []
    for row in cells:
        runs, cur, n = [], False, 0
        for c in row:
            if c == cur:
                n += 1
            else:
                runs.append(n)
                cur, n = c, 1
        runs.append(n)
        rows.append(".".join(np.base_repr(r, 36).lower() for r in runs))
    body = ";".join(rows)
    with open(OUT, "w") as f:
        f.write("// Generated by scripts/generate-tree-foliage-mask.py -- do not edit by hand.\n")
        f.write("// Row-major run-length foliage mask of the tree artwork. Each row alternates\n")
        f.write("// background/foliage run lengths (base 36), starting with background.\n")
        f.write(f"export const FOLIAGE_MASK_IMAGE_WIDTH = {W};\n")
        f.write(f"export const FOLIAGE_MASK_IMAGE_HEIGHT = {H};\n")
        f.write(f"export const FOLIAGE_MASK_COLS = {w};\n")
        f.write(f"export const FOLIAGE_MASK_ROWS = {h};\n")
        f.write(f'export const FOLIAGE_MASK_RLE =\n  "{body}";\n')
    print(f"wrote {OUT}: {w}x{h} cells, {cells.mean():.3f} foliage, {len(body)} chars")


if __name__ == "__main__":
    main()
